# Generated by Django 4.0.5 on 2022-07-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_image_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_user',
            field=models.ImageField(blank=True, null=True, upload_to='image_user'),
        ),
    ]
