# Generated by Django 4.0.5 on 2022-07-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='link',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
