# Generated by Django 4.0.5 on 2022-07-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0005_alter_receta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receta',
            options={'verbose_name': 'receta', 'verbose_name_plural': 'recetas'},
        ),
        migrations.AddField(
            model_name='receta',
            name='porciones',
            field=models.FloatField(default=0),
        ),
    ]
